runtime: python39
entrypoint: gunicorn -b :$PORT app:app --timeout 120 #--log-level warning

# You can specify the Python version here
runtime_config:
  python_version: 3.9

instance_class: B1

# Instance class and scaling configurations can be adjusted based on your needs
# automatic_scaling:
#   target_cpu_utilization: 0.65
#   min_instances: 1
#   max_instances: 1

basic_scaling:
  idle_timeout: 5m
  max_instances: 1